///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace VA_automation.TestModules
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The DesktopApplication recording.
    /// </summary>
    [TestModule("f7a828fb-0d51-42be-a3f0-895d0ed09f94", ModuleType.Recording, 1)]
    public partial class DesktopApplication : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::VA_automation.VA_automationRepository repository.
        /// </summary>
        public static global::VA_automation.VA_automationRepository repo = global::VA_automation.VA_automationRepository.Instance;

        static DesktopApplication instance = new DesktopApplication();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public DesktopApplication()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static DesktopApplication Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.3")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.3")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left DoubleClick item 'DesktopApplication.NotepadPlusPlus' at Center.", repo.DesktopApplication.NotepadPlusPlusInfo, new RecordItemIndex(0));
            repo.DesktopApplication.NotepadPlusPlus.DoubleClick();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Application", "Killing application containing item 'DesktopApplication.NotepadPlusPlus'.", repo.DesktopApplication.NotepadPlusPlusInfo, new RecordItemIndex(1));
            Host.Current.KillApplication(repo.DesktopApplication.NotepadPlusPlus);
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
