///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// Your custom recording code should go in this file.
// The designer will only add methods to this file, so your custom code won't be overwritten.
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace VA_automation.TestModules
{
    public partial class FacbookLogin
    {
        
        private void Init()
        {
            
        }

        public void Get_value_LoginValidation(RepoItemInfo spantagInfo)
        {
            Report.Log(ReportLevel.Info, "Get Value", "Getting attribute 'InnerText' from item 'spantagInfo' and assigning its value to variable 'Loginvalidation'.", spantagInfo);
            Loginvalidation = spantagInfo.FindAdapter<SpanTag>().Element.GetAttributeValueText("InnerText");
            
            //login validation:
            Validate.AreEqual(Loginvalidation,LoginExpectedName);
        }

    }
}
