///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace VA_automation.TestModules
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The HTST recording.
    /// </summary>
    [TestModule("ef271764-2f70-4606-808a-42251d2f8344", ModuleType.Recording, 1)]
    public partial class HTST : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::VA_automation.VA_automationRepository repository.
        /// </summary>
        public static global::VA_automation.VA_automationRepository repo = global::VA_automation.VA_automationRepository.Instance;

        static HTST instance = new HTST();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public HTST()
        {
            DOM = "";
            API = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static HTST Instance
        {
            get { return instance; }
        }

#region Variables

        string _DOM;

        /// <summary>
        /// Gets or sets the value of variable DOM.
        /// </summary>
        [TestVariable("915e1498-6398-4e3c-b2ea-5d705b37c4d7")]
        public string DOM
        {
            get { return _DOM; }
            set { _DOM = value; }
        }

        string _API;

        /// <summary>
        /// Gets or sets the value of variable API.
        /// </summary>
        [TestVariable("5b364f5f-331f-48b7-ac0e-6382a863ae38")]
        public string API
        {
            get { return _API; }
            set { _API = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.3")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.3")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            FacbookSecurityValidation(DOM, API);
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
