///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// Your custom recording code should go in this file.
// The designer will only add methods to this file, so your custom code won't be overwritten.
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Drawing;
using System.IO;
using System.Net;
using System.Text;
using System.Text.RegularExpressions;
using System.Threading;
//using System.Web.Script.Serialization;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace VA_Integration
{
	public class FacbookHTST
	{
		
		
		public string UserEmail { get; set; }
		
		
		
		public FacbookHTST()
		{
			
		}
	}
    public partial class TestOne
    {
        
        private void Init()
        {
            
        }

        public void TestAPI(string DOM, string API)
        {
        	try{
           //local variables
        	
			string keys="";
			string values=""; 
			string url = "https://gmail.googleapis.com/gmail/v1/users/cognigramz@gmail.com/messages";
			
			//Setup API call
			HttpWebRequest httpRequest = (HttpWebRequest)WebRequest.Create(url);
			httpRequest.ContentType = "application/json";
			httpRequest.Method = "GET";
			httpRequest.ContentLength=0;
            
			
			     	
			     		
        	}catch( Exception e){
        		
        		Validate.AreEqual(e.Message,"test");
        	}
        }

    }
}
