///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace VA_Integration
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The TestOne recording.
    /// </summary>
    [TestModule("173d4792-3ca8-4fc6-bffb-bff7b22c8237", ModuleType.Recording, 1)]
    public partial class TestOne : ITestModule
    {
        /// <summary>
        /// Holds an instance of the VA_IntegrationRepository repository.
        /// </summary>
        public static VA_IntegrationRepository repo = VA_IntegrationRepository.Instance;

        static TestOne instance = new TestOne();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public TestOne()
        {
            DOM = "";
            API = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static TestOne Instance
        {
            get { return instance; }
        }

#region Variables

        string _DOM;

        /// <summary>
        /// Gets or sets the value of variable DOM.
        /// </summary>
        [TestVariable("14c4140e-8685-44b2-ad5c-56d5ab124ebb")]
        public string DOM
        {
            get { return _DOM; }
            set { _DOM = value; }
        }

        string _API;

        /// <summary>
        /// Gets or sets the value of variable API.
        /// </summary>
        [TestVariable("aef0e3b1-fd49-4683-ad83-8df886b74a85")]
        public string API
        {
            get { return _API; }
            set { _API = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.3")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.3")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            TestAPI(DOM, API);
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
