///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace VA_Integration
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the VA_IntegrationRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.3")]
    [RepositoryFolder("6094a1aa-b5c4-4beb-8025-e9a3a40adde8")]
    public partial class VA_IntegrationRepository : RepoGenBaseFolder
    {
        static VA_IntegrationRepository instance = new VA_IntegrationRepository();

        /// <summary>
        /// Gets the singleton class instance representing the VA_IntegrationRepository element repository.
        /// </summary>
        [RepositoryFolder("6094a1aa-b5c4-4beb-8025-e9a3a40adde8")]
        public static VA_IntegrationRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public VA_IntegrationRepository() 
            : base("VA_IntegrationRepository", "/", null, 0, false, "6094a1aa-b5c4-4beb-8025-e9a3a40adde8", ".\\RepositoryImages\\VA_IntegrationRepository6094a1aa.rximgres")
        {
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("6094a1aa-b5c4-4beb-8025-e9a3a40adde8")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.3")]
    public partial class VA_IntegrationRepositoryFolders
    {
    }
#pragma warning restore 0436
}