///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace VA_automation
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the VA_automationRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.3")]
    [RepositoryFolder("12d9b7d1-3a4c-469e-b62e-003299030c03")]
    public partial class VA_automationRepository : RepoGenBaseFolder
    {
        static VA_automationRepository instance = new VA_automationRepository();
        VA_automationRepositoryFolders.FacebookLogInOrSignUpAppFolder _facebookloginorsignup;
        VA_automationRepositoryFolders.DesktopApplicationAppFolder _desktopapplication;
        VA_automationRepositoryFolders.FormAsteriskCUsersZchekirDesktopCHaAppFolder _formasteriskcuserszchekirdesktopcha;
        VA_automationRepositoryFolders.CUsersZchekirPycharmProjectsPageobjAppFolder _cuserszchekirpycharmprojectspageobj;

        /// <summary>
        /// Gets the singleton class instance representing the VA_automationRepository element repository.
        /// </summary>
        [RepositoryFolder("12d9b7d1-3a4c-469e-b62e-003299030c03")]
        public static VA_automationRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public VA_automationRepository() 
            : base("VA_automationRepository", "/", null, 0, false, "12d9b7d1-3a4c-469e-b62e-003299030c03", ".\\RepositoryImages\\VA_automationRepository12d9b7d1.rximgres")
        {
            _facebookloginorsignup = new VA_automationRepositoryFolders.FacebookLogInOrSignUpAppFolder(this);
            _desktopapplication = new VA_automationRepositoryFolders.DesktopApplicationAppFolder(this);
            _formasteriskcuserszchekirdesktopcha = new VA_automationRepositoryFolders.FormAsteriskCUsersZchekirDesktopCHaAppFolder(this);
            _cuserszchekirpycharmprojectspageobj = new VA_automationRepositoryFolders.CUsersZchekirPycharmProjectsPageobjAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("12d9b7d1-3a4c-469e-b62e-003299030c03")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The FacebookLogInOrSignUp folder.
        /// </summary>
        [RepositoryFolder("6a45d844-8669-4a17-9eed-2a7c7d0edb0a")]
        public virtual VA_automationRepositoryFolders.FacebookLogInOrSignUpAppFolder FacebookLogInOrSignUp
        {
            get { return _facebookloginorsignup; }
        }

        /// <summary>
        /// The DesktopApplication folder.
        /// </summary>
        [RepositoryFolder("4005713c-4ac6-4b92-b5bf-30644d7ff76e")]
        public virtual VA_automationRepositoryFolders.DesktopApplicationAppFolder DesktopApplication
        {
            get { return _desktopapplication; }
        }

        /// <summary>
        /// The FormAsteriskCUsersZchekirDesktopCHa folder.
        /// </summary>
        [RepositoryFolder("451df014-8099-4a23-8370-b81b1de249e7")]
        public virtual VA_automationRepositoryFolders.FormAsteriskCUsersZchekirDesktopCHaAppFolder FormAsteriskCUsersZchekirDesktopCHa
        {
            get { return _formasteriskcuserszchekirdesktopcha; }
        }

        /// <summary>
        /// The CUsersZchekirPycharmProjectsPageobj folder.
        /// </summary>
        [RepositoryFolder("de94e1af-8ad9-45ba-93f8-69b0d607abf6")]
        public virtual VA_automationRepositoryFolders.CUsersZchekirPycharmProjectsPageobjAppFolder CUsersZchekirPycharmProjectsPageobj
        {
            get { return _cuserszchekirpycharmprojectspageobj; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.3")]
    public partial class VA_automationRepositoryFolders
    {
        /// <summary>
        /// The FacebookLogInOrSignUpAppFolder folder.
        /// </summary>
        [RepositoryFolder("6a45d844-8669-4a17-9eed-2a7c7d0edb0a")]
        public partial class FacebookLogInOrSignUpAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _enterusernameInfo;
            RepoItemInfo _enterpasswordInfo;
            RepoItemInfo _clickloginbuttonInfo;
            RepoItemInfo _loginvalidationInfo;

            /// <summary>
            /// Creates a new FacebookLogInOrSignUp  folder.
            /// </summary>
            public FacebookLogInOrSignUpAppFolder(RepoGenBaseFolder parentFolder) :
                    base("FacebookLogInOrSignUp", "/dom[@domain='www.facebook.com']", parentFolder, 30000, null, false, "6a45d844-8669-4a17-9eed-2a7c7d0edb0a", "")
            {
                _enterusernameInfo = new RepoItemInfo(this, "EnterUsername", ".//input[#'email']", 30000, null, "90ce75b0-258b-4cac-b00c-17b281c79ba5");
                _enterpasswordInfo = new RepoItemInfo(this, "EnterPassword", ".//input[#'pass']", 30000, null, "30588174-f988-45a3-814f-307e118b5460");
                _clickloginbuttonInfo = new RepoItemInfo(this, "ClickLoginButton", ".//button[@innertext='Log In']", 30000, null, "52fb3fde-7d58-43d3-9d1b-0607e535685e");
                _loginvalidationInfo = new RepoItemInfo(this, "LoginValidation", ".//span[@innertext='Zak']", 30000, null, "5b9abaa4-555d-4696-9fa1-b87da35efb3b");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("6a45d844-8669-4a17-9eed-2a7c7d0edb0a")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("6a45d844-8669-4a17-9eed-2a7c7d0edb0a")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The EnterUsername item.
            /// </summary>
            [RepositoryItem("90ce75b0-258b-4cac-b00c-17b281c79ba5")]
            public virtual Ranorex.InputTag EnterUsername
            {
                get
                {
                    return _enterusernameInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The EnterUsername item info.
            /// </summary>
            [RepositoryItemInfo("90ce75b0-258b-4cac-b00c-17b281c79ba5")]
            public virtual RepoItemInfo EnterUsernameInfo
            {
                get
                {
                    return _enterusernameInfo;
                }
            }

            /// <summary>
            /// The EnterPassword item.
            /// </summary>
            [RepositoryItem("30588174-f988-45a3-814f-307e118b5460")]
            public virtual Ranorex.InputTag EnterPassword
            {
                get
                {
                    return _enterpasswordInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The EnterPassword item info.
            /// </summary>
            [RepositoryItemInfo("30588174-f988-45a3-814f-307e118b5460")]
            public virtual RepoItemInfo EnterPasswordInfo
            {
                get
                {
                    return _enterpasswordInfo;
                }
            }

            /// <summary>
            /// The ClickLoginButton item.
            /// </summary>
            [RepositoryItem("52fb3fde-7d58-43d3-9d1b-0607e535685e")]
            public virtual Ranorex.ButtonTag ClickLoginButton
            {
                get
                {
                    return _clickloginbuttonInfo.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The ClickLoginButton item info.
            /// </summary>
            [RepositoryItemInfo("52fb3fde-7d58-43d3-9d1b-0607e535685e")]
            public virtual RepoItemInfo ClickLoginButtonInfo
            {
                get
                {
                    return _clickloginbuttonInfo;
                }
            }

            /// <summary>
            /// The LoginValidation item.
            /// </summary>
            [RepositoryItem("5b9abaa4-555d-4696-9fa1-b87da35efb3b")]
            public virtual Ranorex.SpanTag LoginValidation
            {
                get
                {
                    return _loginvalidationInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The LoginValidation item info.
            /// </summary>
            [RepositoryItemInfo("5b9abaa4-555d-4696-9fa1-b87da35efb3b")]
            public virtual RepoItemInfo LoginValidationInfo
            {
                get
                {
                    return _loginvalidationInfo;
                }
            }
        }

        /// <summary>
        /// The DesktopApplicationAppFolder folder.
        /// </summary>
        [RepositoryFolder("4005713c-4ac6-4b92-b5bf-30644d7ff76e")]
        public partial class DesktopApplicationAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _notepadplusplusInfo;

            /// <summary>
            /// Creates a new DesktopApplication  folder.
            /// </summary>
            public DesktopApplicationAppFolder(RepoGenBaseFolder parentFolder) :
                    base("DesktopApplication", "/desktop[@processname='explorer']", parentFolder, 30000, null, true, "4005713c-4ac6-4b92-b5bf-30644d7ff76e", "")
            {
                _notepadplusplusInfo = new RepoItemInfo(this, "NotepadPlusPlus", "?/?/list[@controlid='1']/listitem[@text='Notepad++']", 30000, null, "c26a56b3-f839-40ae-8567-459e38cb243a");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("4005713c-4ac6-4b92-b5bf-30644d7ff76e")]
            public virtual Ranorex.Desktop Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Desktop>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("4005713c-4ac6-4b92-b5bf-30644d7ff76e")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The NotepadPlusPlus item.
            /// </summary>
            [RepositoryItem("c26a56b3-f839-40ae-8567-459e38cb243a")]
            public virtual Ranorex.ListItem NotepadPlusPlus
            {
                get
                {
                    return _notepadplusplusInfo.CreateAdapter<Ranorex.ListItem>(true);
                }
            }

            /// <summary>
            /// The NotepadPlusPlus item info.
            /// </summary>
            [RepositoryItemInfo("c26a56b3-f839-40ae-8567-459e38cb243a")]
            public virtual RepoItemInfo NotepadPlusPlusInfo
            {
                get
                {
                    return _notepadplusplusInfo;
                }
            }
        }

        /// <summary>
        /// The FormAsteriskCUsersZchekirDesktopCHaAppFolder folder.
        /// </summary>
        [RepositoryFolder("451df014-8099-4a23-8370-b81b1de249e7")]
        public partial class FormAsteriskCUsersZchekirDesktopCHaAppFolder : RepoGenBaseFolder
        {

            /// <summary>
            /// Creates a new FormAsteriskCUsersZchekirDesktopCHa  folder.
            /// </summary>
            public FormAsteriskCUsersZchekirDesktopCHaAppFolder(RepoGenBaseFolder parentFolder) :
                    base("FormAsteriskCUsersZchekirDesktopCHa", "/form[@title~'^\\*C:\\\\Users\\\\zchekir\\\\Desktop']", parentFolder, 30000, null, true, "451df014-8099-4a23-8370-b81b1de249e7", "")
            {
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("451df014-8099-4a23-8370-b81b1de249e7")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("451df014-8099-4a23-8370-b81b1de249e7")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }
        }

        /// <summary>
        /// The CUsersZchekirPycharmProjectsPageobjAppFolder folder.
        /// </summary>
        [RepositoryFolder("de94e1af-8ad9-45ba-93f8-69b0d607abf6")]
        public partial class CUsersZchekirPycharmProjectsPageobjAppFolder : RepoGenBaseFolder
        {

            /// <summary>
            /// Creates a new CUsersZchekirPycharmProjectsPageobj  folder.
            /// </summary>
            public CUsersZchekirPycharmProjectsPageobjAppFolder(RepoGenBaseFolder parentFolder) :
                    base("CUsersZchekirPycharmProjectsPageobj", "/form[@title~'^C:\\\\Users\\\\zchekir\\\\PycharmP']", parentFolder, 30000, null, true, "de94e1af-8ad9-45ba-93f8-69b0d607abf6", "")
            {
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("de94e1af-8ad9-45ba-93f8-69b0d607abf6")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("de94e1af-8ad9-45ba-93f8-69b0d607abf6")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}